spring:
  datasource:
    url: jdbc:mysql:aws://${DB_URL:localhost:23306}/test_db
    driver-class-name: software.aws.rds.jdbc.mysql.Driver
logging:
  level:
    software.amazon.rds.jdbc.mysql: trace
